### ISSUE TITLE
Can it work with image but not PDF?

### ISSUE THREAD

**Issue by AmigoCDT** [RQ-Luo/contour-dewarp#1]
Thank you soooo much for the great idea.
I try to run code with image but not pdf as input. I straight call replacePic(im) with a FaPiao(发票) image， but it raise ERROR as following:
```Traceback (most recent call last):
  File "./dewarp.py", line 364, in <module>
    new_img = processImg(img_path)
  File "./dewarp.py", line 131, in processImg
    new_img = replacePic(img)
  File "./dewarp.py", line 109, in replacePic
    enhan, binary = enhanScan(img, contours)
  File "./dewarp.py", line 32, in enhanScan
    Page = curveToFlat(maxCnt(contours), gray)
  File "./dewarp.py", line 56, in curveToFlat
    return OldmergeBlocks(blocks, gray)
  File "./dewarp.py", line 225, in OldmergeBlocks
    out[0:4960, begin:xend+begin] = image
ValueError: could not broadcast input array from shape (4960,7016) into shape (4960,0)
```

I found that happened when process this block ([[2656 2499], [2656 2499], [2636 3074], [2636 3892]]). This is a triangle but not a rectangle, Is this normal?
Maybe the way I call replacePic() is wrong?
Thank you

**Comment by RQ-Luo** [comment]
I'm sorry, but the script is not as universal as the theory described in the paper.;
This script is used to validate key algorithms, and it is based on solving a specific problem such as page bending.


The error is reported because the code divides the one big page into left and right pages, but you can use the core part of the code, which is the part that subdivides the surface according to contour. sub functions in curveToFlat and its subsub


The script is terrible, unreadable, it has not been tested with more use cases,mIt is just to verify that the flattening method based on the contour is feasible.


For the technical problems in engineering, I need the help of others who are more professional, which is also why I put this code and paper in github.



Also, I will put core functions in another independent py file with a much more neat and readable way as soon as posible.


Sincerely sorry,
renqing
